apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kartograph-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jsell-rh/kartograph.git
    targetRevision: feat/23-kustomize-migration
    path: app/deploy/overlays/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: kartograph-stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
