apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kartograph-stage

resources:
  - ../../base
  - route.yaml

patches:
  - path: configmap-patch.yaml
  - path: resources-patch.yaml

images:
  - name: ghcr.io/jsell-rh/kartograph
    newTag: v0.2.5 # Updated by GitHub Action
