---
apiVersion: v1
kind: Secret
metadata:
  name: kartograph-secrets
type: Opaque
stringData:
  auth-secret: <path:hcm-ai/data/kartograph/stage/better-auth#BETTER_AUTH_SECRET>
---
apiVersion: v1
kind: Secret
metadata:
  name: kartograph-github-oauth
type: Opaque
stringData:
  client-id: <path:hcm-ai/data/kartograph/stage/github-oidc#GITHUB_CLIENT_ID>
  client-secret: <path:hcm-ai/data/kartograph/stage/github-oidc#GITHUB_CLIENT_SECRET>
---
apiVersion: v1
kind: Secret
metadata:
  name: kartograph-vertex-ai
type: Opaque
stringData:
  credentials.json: <path:hcm-ai/data/kartograph/stage/vertex-ai#credentials.json>
  project-id: <path:hcm-ai/data/kartograph/stage/vertex-ai#VERTEX_PROJECT_ID>
  region: <path:hcm-ai/data/kartograph/stage/vertex-ai#VERTEX_REGION>
